### ISSUE TITLE
METEOR_SETTINGS  env var is breaking the build

### ISSUE THREAD

**Issue by bogdanrn** [AdmitHub/meteor-buildpack-horse#40]
There is almost no documentation on how to correctly use this env variable. 

I tried giving it a path to a json file but i coudln't get it to work at all. The alternative i found was to specifiy the json directly like : 

```METEOR_SETTINGS = '{ "public" : { "foo" : "bar" } }'```

This works and settings are loaded in my app. If i try to push the code while this variable is set, i get an error : 
```
remote: Errors prevented isopacket load:
remote: 
remote: While loading isopacket `constraint-solver`:
remote: packages/meteor/server_environment.js:13:1: METEOR_SETTINGS are not valid JSON:
remote: {public:{ga:{id:UA-XXXXXX-YY}}}
remote: at packages/meteor/server_environment.js:13:1
remote: at <runJavaScript-2>:41:4
remote: at <runJavaScript-2>:1240:3
```
My current workaround is to unset the variable, deploy my code, re-set the variable. Is someone else experiencing this ?

**Comment by yourcelf** [comment]
Setting a valid JSON string to ``METEOR_SETTINGS`` is the correct way to do it.  It sounds like the string you have set as METEOR_SETTINGS is not valid JSON, which is making the build fail.

We use METEOR_SETTINGS in all of our deployments, and don't have this problem.  As long as it's correct JSON it should work fine.  Beware of any munging of strings your terminal might be doing if you're trying to set the variable from the command line.

**Comment by oojr** [comment]
@bogdanrn I am experiencing the same error and I am passing it valid JSON according to JSONLint

**Comment by bogdanrn** [comment]
@oojr i never found the problem, ended up removing the settings before deploy and put them back after

**Comment by oojr** [comment]
@bogdanrn I deploy on dokku/digital ocean and the buildpack targets heroku, so the maintainer @yourcelf might not be able to reproduce the error, I'll look into the code and see what I can do but for now I unset then set the settings just like you 😅

**Comment by branco91** [comment]
@oojr , @yourcelf I can also confirm this is an issue for me. I am using DigitalOcean and the Meteor settings works great in local, running meteor --settings settings.json. However, defining that same json in the environment variable causes the build to fail. 
What i noticed is that even though my settings look like 

```
{
  "public": {
    "host": {
      "url": "https://hello.abcd.com"
    },
    "facebook": {
      "appID": <ABCD>
    },
}
```

when its being interpreted in the build it comes as below, without the quotes causing it to be an invalid JSON :
```
{
  public {
    host: {
      url: https://hello.abcd.com
    },
    facebook: {
      appID: <ABCD>
    },
}
```

remote: Errors prevented isopacket load:
remote: 
remote: While loading isopacket `cordova-support`:
remote: packages/meteor/server_environment.js:13:1: METEOR_SETTINGS are not valid JSON:

Kind Regards
Junio

**Comment by branco91** [comment]
@bogdanrn , @oojr , I managed to get the settings working with the build but requires escaping of the double quotes characters.

I believe the issue does not reside in the meteor-buildpack-horse but more on how Dokku parses the environment variables : https://github.com/dokku/dokku/issues/1737

By making the settings.json as
```
 {
  \"public\": {
    \"host\": {
      url: https://hello.abcd.com
    },
    \"facebook\": {
      appID: <ABCD>
    },
```

It makes my build pass.

**Comment by branco91** [comment]
Interestingly enough, if i escape the double quotes I manage to get the build to complete but when it attempts to start meteor, because the escaped json is not a valid one, it fails.

**Comment by oojr** [comment]
@branco91 the work around has been to to unset settings, deploy the code without the settings, then add settings after the code is in production, I personally have been exploring a different nodejs stack not using meteor and deploying on openshift (https://www.openshift.com/)

**Comment by yourcelf** [comment]
Closing this now, as it appears the upstream issue has been resolved.

**Comment by benmgreene** [comment]
Really? What was the solution?

**Comment by yourcelf** [comment]
I'm referring to dokku/dokku#1737, which others referenced.  I don't use dokku myself so I haven't evaluated it further.  If you still think there's a bug in this buildpack that isn't really a bug in dokku, feel free to reopen.

**Comment by whsahhar** [comment]
FWIW: I just removed all the white spaces in the JSON string. 
i.e. changed this:

    {
      "key" : "value"
    }

to `{"key":"value"}`

..and it now works

**Comment by leosco** [comment]
No whitespace in mine either and and I'm still getting this error. Validated my entire JSON through JSONLint and ran it through `JSON.stringify()` before pasting it into the upstart script.

**Comment by MMrj9** [comment]
In order to make it work I needed to use single quotes to wrap the whole json
