### ISSUE TITLE
build failing - appears related to phantom JS

### ISSUE THREAD

**Issue by j20** [AdmitHub/meteor-buildpack-horse#51]
I have a couple Meteor apps (latest version of Meteor 1.0.2) that fail to build. The error message is:

		remote: -----> Adding PATH environment
		remote: -----> Running extras
		remote: -----> Adding MONGOHQ_URL -> MONGO_URL env
		remote: -----> Adding MONGOLAB_URI -> MONGO_URL env
		remote: -----> Installing phantomjs.
		remote: bzip2: (stdin) is not a bzip2 file.
		remote: tar: Child returned status 2
		remote: tar: Error is not recoverable: exiting now
		remote:
		remote:  !     Push rejected, failed to compile Node.js app

I've forked the buildpack to try using Phantom's latest version, 2.0.0, but received the same error.

Any ideas? Anybody else experiencing this?

**Comment by sgtpepper43** [comment]
I'm also having this problem. It's really intermittent, though, maybe because Heroku has the builds cached or something. I pushed up `HEAD~1` and it builds, then `HEAD~2` and that builds, then I try `HEAD~1` again and it fails, and so on down the line. Except one time when I went forward again it build correctly... I have no idea what's going on.

**Comment by lnmunhoz** [comment]
I'm having the same problem and I need to deploy right now. @sgtpepper43 Can you explain how to solve it?

**Comment by lnmunhoz** [comment]
Magically works now...

**Comment by sgtpepper43** [comment]
Oh, no, I have no idea. It just works sometimes.

**Comment by j20** [comment]
hmm still failing here. 

I noticed that BitBucket, which is hosting PhantomJS downloads, gave me a 500 error when I visited the URL in a web browser today and then loaded successfully when I visited that URL another time. It's possible this is related to a BitBucket issue.

**Comment by sgtpepper43** [comment]
Ah, that would explain the `is not a bzip2 file` error. It's because it's not downloading the file.

**Comment by j20** [comment]
Using the buildpack mentioned in issue https://github.com/AdmitHub/meteor-buildpack-horse/issues/53 worked for me.  

`https://github.com/alykoshin/meteor-buildpack-horse-1202-fixed`

**Comment by yourcelf** [comment]
By default, we are including the `phantomjs` extra that downloads phantomjs from their distribution on bitbucket.  If bitbucket responds with a 404 or 503 or something (as it did for me today), this error can come up -- so unfortunately, we're dependent on bitbucket's reliability.

If you don't need phantomjs for spiderable, you can fork this pack and remove the phantomjs extra; or replace it with a version that fetches phantomjs from a more reliable endpoint than bitbucket.

**Comment by macsj200** [comment]
Still getting this issue, can we remove phantomjs as a dep?
