### ISSUE TITLE
Detemine meteor version from .meteor/release

### ISSUE THREAD

**Issue by j20** [AdmitHub/meteor-buildpack-horse#67]
The buildpack currently installs the latest production version of Meteor.

This causes a problem because if a developer is using a beta version (such as a 1.3 beta), the buildpack ignores the version of Meteor that the developer developed for and uses 1.2.1, which is the latest production version.

It'd be better if the meteor version were determined based on the version specified in ./meteor/release Example: https://github.com/jordansissel/heroku-buildpack-meteor/blob/master/bin/compile_meteor#L23

**Comment by yourcelf** [comment]
Thanks. Fixed in https://github.com/AdmitHub/meteor-buildpack-horse/commit/83843441efa25e0bf5575c435ef2bbf951ceedbf

**Comment by tab00** [comment]
It shouldn't be assumed that an upgrade is wanted. Some users may want to use an older stable version than the latest version.

Version 1.3.4.3 was just released hours ago and I've been having a problem deploying my Meteor 1.3.4.1 app to a hosting environment because this script installs Meteor 1.3.4.3. I have modified my fork to read the version that the app uses before calling Meteor's install script with query string release=$APP_VERSION. I also disabled the update code in my fork.

See https://github.com/tab00/meteor-buildpack-horse/blob/master/bin/compile#L113

**Comment by yourcelf** [comment]
This buildpack doesn't assume you want a newer release.  Meteor's "version" and "release" can be confusing; there are two parts to consider:

1. The version of "meteor tool" (the `meteor` command)
2. The release version of your app

When you run any `meteor` command within a meteor project, the "tool" reads from `.meteor/release` and runs using the release that your app targets, transparently downloading any older release files as needed.  So typing `meteor` (even when your system meteor is a newer release than your app) is effectively running as the older release.  This is how it is possible to develop multiple meteor projects targeting different releases.

The only reason the "upgrade" code is needed at all is when you're targeting a release that is newer than the version of `meteor tool` that is installed; since that meteor tool version doesn't know how to install the newer meteor release.

But I like the changes you made; they could be useful to help with #9 by downloading only the targeted release, rather than downloading the "current" one with the current release then subsequently downloading a new release.  It also simplifies things, which is always great.

**Comment by tab00** [comment]
Thank you for explaining the difference. Though the fact is that when there is a new version of Meteor released, bugs may still exist that MDG had not caught in their own testing.

Calling `curl -sS https://install.meteor.com` forces installation of the latest version only, which may not be wanted because an app that targets an older Meteor version may not work properly. In my case when I wrote my post above, 1.3.4.3 failed to run my app that targets Meteor 1.3.4.1. So I had to add the query string `release=$METEOR_VERSION`. That fixed my problem.

So I think you should change `curl -sS https://install.meteor.com` to `curl -sS https://install.meteor.com?release=$METEOR_VERSION`.

**Comment by yourcelf** [comment]
The [next version](https://github.com/AdmitHub/meteor-buildpack-horse/pull/130) will use `https://install.meteor.com?release=$METEOR_VERSION`. Thanks for the suggestion. :)
